import Foundation

/// Complements `resultCode` property with information about unified name and source of the operation result code.
public struct ReturnCode {
	/// Unified return code name to indicate success or reason for an error. The code is unified across OPG platform, it is independent from underlying PSP or institution service. E.g. "OK", "NON_SUFFICIENT_FUNDS", "INVALID_ACCOUNT_NUMBER", etc.
	public let name: String
	
	/// System that generated this return code.
	public let source: Source
	
	public enum Source {
		/// indicates that return code is generated by OPG platform.
		case GATEWAY
		
		/// if return code is a result of mapping from payment service provider code.
		case PSP
		
		/// for those codes that were originally generated by financial institution (issuing or acquiring banks).
		case INSTITUTION
	}
}
